[target.thumbv7em-none-eabihf]
# TODO on real watch hardware, replace with STM32H7S7L8Hx
runner = "probe-rs run --chip STM32H7S3L8Hx"
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
# (`thumbv6m-*` is compatible with all ARM Cortex-M chips but using the right target improves performance)
# target = "thumbv6m-none-eabi"    # Cortex-M0 and Cortex-M0+
# target = "thumbv7m-none-eabi"    # Cortex-M3
# target = "thumbv7em-none-eabi"   # Cortex-M4 and Cortex-M7 (no FPU)
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

[alias]
rr = "run --release"
rb = "run --bin"
rrb = "run --release --bin"
bbr = "build --release --bin"

[env]
DEFMT_LOG = "trace"
